---
title: "Data Viz for usacanmex.csv by Scenario"
author: "Charavee Basnet Chettri"
format: html
editor: visual
---

### Loading packages

```{r}
library (tidyverse)
```

### Importing data

```{r}
r2_data <- read_csv ("usacanmex_1.csv")
```

### Selecting Data

```{r}
r2_filt <-r2_data %>% 
  filter (region == "United States",
          variable == "Emissions|BC" | 
          variable == "Emissions|CO" |
          variable == "Emissions|NOx" |
          variable == "Emissions|PM10" | 
          variable == "Emissions|PM2.5" | 
          variable == "Emissions|Sulfur" |
          variable == "Emissions|VOC") %>% 
  filter (year <= 2050) %>% 
  filter (scenario != "Nt.Ref.R2") %>% 
  filter (grepl ("R2", scenario)) %>%
  filter (!grepl ("TSG", scenario )) %>%
  filter (!grepl ("CMS", scenario)) %>%
  filter (!grepl ("ISG", scenario)) %>%
  filter (!grepl ("BSG", scenario))

r2_filt_2 <- r2_filt %>% 
  group_by (model, scenario, variable, year) %>% 
  summarize (total = sum (value))

# scenario == "NT.Ref"|
#           scenario == "0by50.Ref"|
#           scenario == "0by50.Adv"|
#           scenario == "0by50.BSG.Adv"|
#           scenario == "0by50.CMSG.Adv"|
#           scenario == "0by50.ISG.Adv"|
#           scenario == "0by50.TSG.Adv"
```

```{r}
ggplot (data = r2_filt, mapping = aes (x = year, 
                                       y = value, 
                                       color = scenario))+
  geom_line()+
  facet_wrap (~variable)+
  labs (title = "Emissions of Each Pollutant by 2050 by Scenario",
          subtitle = "Date: Oct 18, 2022",
          x = "Year",
          y = "Emissions(Mt BC/yr)",
          color = "Pollutant")
```

```{r}
ggplot (data = r2_filt_2, mapping = aes (x = year, 
                                       y = total, 
                                       color = variable))+
  geom_line()+
  facet_wrap (~scenario)+
  labs (title = "Emissions of Each Pollutant by 2050 by Scenario",
          subtitle = "Date: Oct 18, 2022",
          x = "Year",
          y = "Emissions(Mt BC/yr)",
          color = "Pollutant")
```

```{r}
ggplot (data = r2_filt, mapping = aes (x = year, 
                                       y = value, 
                                       color = variable))+
  geom_line()+
  facet_wrap (~model)+
  labs (title = "Emissions of Each Pollutant by 2050 by Scenario",
          subtitle = "Date: Oct 18, 2022",
          x = "Year",
          y = "Emissions(Mt BC/yr)",
          color = "Pollutant")
```

```{r}
ggplot (data = r2_filt, mapping = aes (x = year, 
                                       y = value, 
                                       color = variable))+
  geom_line(aes(y=value))+
  geom_line (aes (y=scenario))+
  scale_y_continuous (
    name = "Emissions(Mt BC/yr)",
    sec.axis = sec_axis (trans=~.*1, name = "Scenario")
  )+
  facet_wrap (~model)+
  labs (title = "Emissions of Each Pollutant by 2050 by Scenario",
          subtitle = "Date: Oct 18, 2022",
          x = "Year",
          y = "Emissions(Mt BC/yr)",
          color = "Pollutant")
```


```{r}
ggplot (data = r2_filt, mapping = aes (x = year, y = value, color = scenario))+
    geom_line()+
    facet_wrap (~variable)+
    labs (title = "Emissions of Each Pollutant by 2050 by Scenario",
          subtitle = "Date: Oct 18, 2022",
          x = "Year",
          y = "Emissions(Mt BC/yr)",
          color = "Pollutant")
```













### Four Variable Graph

```{r}

ggplot (data = r2_filt, mapping = aes (x = year, y = value, color = scenario))+
  geom_point()+
  facet_wrap (~variable)+
  labs (title = "Emissions of Each Pollutant by 2050 by Scenario",
        subtitle = "Date: Oct 13, 2022",
        x = "Year",
        y = "Emissions(Mt BC/yr)",
        color = "Pollutant")

```

```{r}

```

```{r}


r2_filt %>% 
  filter(scenario == "0by50.Ref.R2") %>% 
  ggplot (mapping = aes (x = year, y = value))+
    geom_point()+
    facet_wrap (~variable)+
    labs (title = "Emissions of Each Pollutant by 2050 by Scenario",
          subtitle = "Date: Oct 13, 2022",
          x = "Year",
          y = "Emissions(Mt BC/yr)",
          color = "Pollutant")
```

```{r}
r2_filt %>% 
  filter(scenario == "0by50.Ref.R2",
         value != 0) %>% 
  ggplot (mapping = aes (x = year, y = value))+
    geom_point()+
    facet_wrap (~variable)+
    labs (title = "Emissions of Each Pollutant by 2050 by Scenario",
          subtitle = "Date: Oct 13, 2022",
          x = "Year",
          y = "Emissions(Mt BC/yr)",
          color = "Pollutant")
```


```{r}
ggplot (data = r2_filt, mapping = aes (x = year, y = value, color = variable))+
  geom_line()+
  facet_wrap (~scenario)+
  labs (title = "Emissions of Each Pollutant by 2050 by Scenario",
        subtitle = "Date: Oct 13, 2022",
        x = "Year",
        y = "Emissions(Mt BC/yr)",
        color = "Pollutant")
```

\-\-\-\-\-\-\-\--

### Old Graphs

### BC

```{r}

scen_BC <- r2_filt %>% 
  select (-model, -region) %>% 
  filter (variable == "Emissions|BC") 

ggplot (data = scen_BC, mapping = aes (x = year, y = value))+
  geom_line()+
  facet_wrap (~scenario)+
  labs (title = "1a) BC emissions by Scenario",
        x = "Year",
        y = "Emissions|BC (Mt BC/yr)")

```

### CO

```{r}

scen_CO <- r2_filt %>% 
  select (-model, -region) %>% 
  filter (variable == "Emissions|CO") 

ggplot (data = scen_CO, mapping = aes (x = year, y = value))+
  geom_line()+
  facet_wrap (~scenario)+
  labs (title = "2a) CO emissions by Scenario",
        x = "Year",
        y = "Emissions|CO (Mt BC/yr)")
```

### PM 2.5

```{r}
scen_pm25 <- r2_filt %>% 
  select (-model, -region) %>% 
  filter (variable == "Emissions|PM2.5") 

ggplot (data = scen_pm25, mapping = aes (x = year, y = value))+
  geom_line()+
  facet_wrap (~scenario)+
  labs (title = "3a) PM 2.5 emissions by Scenario",
        x = "Year",
        y = "Emissions|PM2.5 (Mt BC/yr)")
```

### PM 10

```{r}
scen_pm10 <- r2_filt %>% 
  select (-model, -region) %>% 
  filter (variable == "Emissions|PM10") 

ggplot (data = scen_pm10, mapping = aes (x = year, y = value))+
  geom_line()+
  facet_wrap (~scenario)+
  labs (title = "4a) PM 10 emissions by Scenario",
        x = "Year",
        y = "Emissions|PM10 (Mt BC/yr)")
```

### VOC

```{r}
scen_voc <- r2_filt %>% 
  select (-model, -region) %>% 
  filter (variable == "Emissions|VOC") 

ggplot (data = scen_voc, mapping = aes (x = year, y = value))+
  geom_line()+
  facet_wrap (~scenario)+
  labs (title = "5a) VOC emissions by Scenario",
        x = "Year",
        y = "Emissions|VOC (Mt BC/yr)")
```

### NOx

```{r}
scen_nox <- r2_filt %>% 
  select (-model, -region) %>% 
  filter (variable == "Emissions|NOx")

ggplot (data = scen_nox, mapping = aes (x = year, y = value))+
  geom_line()+
  facet_wrap (~scenario)+
  labs (title = "6a) NOx emissions by Scenario",
        x = "Year",
        y = "Emissions|NOx (Mt BC/yr)")
```

### Sulfur

```{r}
scen_sulfur <- r2_filt %>% 
  select (-model, -region) %>% 
  filter (variable == "Emissions|Sulfur")

ggplot (data = scen_sulfur, mapping = aes (x = year, y = value))+
  geom_line()+
  facet_wrap (~scenario)+
  labs (title = "7a) Sulfur emissions by Scenario",
        x = "Year",
        y = "Emissions|Sulfur (Mt BC/yr)")
```

### 
